export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const UPDATE_USER_IN_COMPANY_REQUEST = "UPDATE_USER_IN_COMPANY_REQUEST";
export const UPDATE_USER_IN_COMPANY_FAIL = "UPDATE_USER_IN_COMPANY_FAIL";
export const UPDATE_USER_IN_COMPANY_SUCCESS = "UPDATE_USER_IN_COMPANY_SUCCESS";

export const ADD_COMPANY_TO_USER_REQUEST = "ADD_COMPANY_TO_USER_REQUEST";
export const ADD_COMPANY_TO_USER_SUCCESS = "ADD_COMPANY_TO_USER_SUCCESS";
export const ADD_COMPANY_TO_USER_FAIL = "ADD_COMPANY_TO_USER_FAIL";

export const DELETE_COMPANY_FROM_USER_REQUEST = "DELETE_COMPANY_FROM_USER_REQUEST";
export const DELETE_COMPANY_FROM_USER_SUCCESS = "DELETE_COMPANY_FROM_USER_SUCCESS";
export const DELETE_COMPANY_FROM_USER_FAIL = "DELETE_COMPANY_FROM_USER_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const SHOW_DIALOG = "SHOW_DIALOG";
export const HIDE_DIALOG = "HIDE_DIALOG";
export const RESET_AUTH_NOTIFICATION = "RESET_AUTH_NOTIFICATION";
export const RESET_USER_NOTIFICATION = "RESET_USER_NOTIFICATION";



export const CREATE_COMPANY_REQUEST = "CREATE_COMPANY_REQUEST";
export const CREATE_COMPANY_SUCCESS = "CREATE_COMPANY_SUCCESS";
export const CREATE_COMPANY_FAIL = "CREATE_COMPANY_FAIL";

export const GET_COMPANIES_REQUEST = "GET_COMPANIES_REQUEST";
export const GET_COMPANIES_SUCCESS = "GET_COMPANIES_SUCCESS";
export const GET_COMPANIES_FAIL = "GET_COMPANIES_FAIL";

export const GET_COMPANY_REQUEST = "GET_COMPANY_REQUEST";
export const GET_COMPANY_SUCCESS = "GET_COMPANY_SUCCESS";
export const GET_COMPANY_FAIL = "GET_COMPANY_FAIL";

export const UPDATE_COMPANY_REQUEST = "UPDATE_COMPANY_REQUEST";
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS";
export const UPDATE_COMPANY_FAIL = "UPDATE_COMPANY_FAIL";

export const DELETE_COMPANY_REQUEST = "DELETE_COMPANY_REQUEST";
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS";
export const DELETE_COMPANY_FAIL = "DELETE_COMPANY_FAIL";


export const RESET_COMPANY_NOTIFICATION = "RESET_COMPANY_NOTIFICATION";
