//AUTH

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'




export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const RESET_AUTH_NOTIFICATION = "RESET_AUTH_NOTIFICATION";
//USER
export const GET_USERS = "GET_USER";
export const GET_USER = "GET_USER";
export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_IN_COMPANY = "UPDATE_USER_IN_COMPANY";
export const ADD_COMPANY_TO_USER = "ADD_COMPANY_TO_USER";
export const DELETE_COMPANY_FROM_USER = "DELETE_COMPANY_FROM_USER";
export const DELETE_USER = "DELETE_USER";
//DIALOG
export const SHOW_DIALOG = "SHOW_DIALOG";
export const HIDE_DIALOG = "HIDE_DIALOG";
export const RESET_USER_NOTIFICATION = "RESET_USER_NOTIFICATION";
//COMPANY
export const CREATE_COMPANY = "CREATE_COMPANY";
export const GET_COMPANIES = "GET_COMPANIES";
export const GET_COMPANY = "GET_COMPANY";
export const UPDATE_COMPANY = "UPDATE_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const RESET_COMPANY_NOTIFICATION = "RESET_COMPANY_NOTIFICATION";
//TABLE
export const GET_EXPANDED_STATUS = 'GET_EXPANDED_STATUS'
